<a href="https://colab.research.google.com/github/aHawkins63/Feature-Engineering/blob/main/NN_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Importing the necessary libraries
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import load_digits
from sklearn.datasets import load_wine
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

print("--------------------------------------------------")
print("Running Classification for Iris Dataset")
print("--------------------------------------------------")

# Loading the Iris dataset
dataset_iris = load_iris()

# Splitting the data into test and train (80 - 20 Split)
x_train_iris, x_test_iris, y_train_iris, y_test_iris = train_test_split(dataset_iris.data, dataset_iris.target, test_size=0.20, random_state=4)

# Making the Neural Network Classifier
NN_iris = MLPClassifier(max_iter=1000, random_state=4) # Increased max_iter for convergence

# Training the model
NN_iris.fit(x_train_iris, y_train_iris)

# Testing the model
y_pred_iris = NN_iris.predict(x_test_iris)

# Evaluating the results
accuracy_iris = accuracy_score(y_test_iris, y_pred_iris) * 100
confusion_mat_iris = confusion_matrix(y_test_iris, y_pred_iris)

# Printing the Results
print("Accuracy for Neural Network (Iris):", accuracy_iris)
print("Confusion Matrix (Iris):")
print(confusion_mat_iris)


print("\n--------------------------------------------------")
print("Running Classification for Digits Dataset")
print("--------------------------------------------------")

# Loading the Digits dataset
dataset_digits = load_digits()

# Splitting the data into test and train (80 - 20 Split)
x_train_digits, x_test_digits, y_train_digits, y_test_digits = train_test_split(dataset_digits.data, dataset_digits.target, test_size=0.20, random_state=4)

# Making the Neural Network Classifier
NN_digits = MLPClassifier(max_iter=1000, random_state=4) # Increased max_iter for convergence

# Training the model
NN_digits.fit(x_train_digits, y_train_digits)

# Testing the model
y_pred_digits = NN_digits.predict(x_test_digits)

# Evaluating the results
accuracy_digits = accuracy_score(y_test_digits, y_pred_digits) * 100
confusion_mat_digits = confusion_matrix(y_test_digits, y_pred_digits)

# Printing the Results
print("Accuracy for Neural Network (Digits):", accuracy_digits)
print("Confusion Matrix (Digits):")
print(confusion_mat_digits)


print("\n--------------------------------------------------")
print("Running Classification for Wine Dataset")
print("--------------------------------------------------")

# Loading the Wine dataset
dataset_wine = load_wine()

# Splitting the data into test and train (80 - 20 Split)
x_train_wine, x_test_wine, y_train_wine, y_test_wine = train_test_split(dataset_wine.data, dataset_wine.target, test_size=0.20, random_state=4)

# Making the Neural Network Classifier
NN_wine = MLPClassifier(max_iter=1000, random_state=4) # Increased max_iter for convergence

# Training the model
NN_wine.fit(x_train_wine, y_train_wine)

# Testing the model
y_pred_wine = NN_wine.predict(x_test_wine)

# Evaluating the results
accuracy_wine = accuracy_score(y_test_wine, y_pred_wine) * 100
confusion_mat_wine = confusion_matrix(y_test_wine, y_pred_wine)

# Printing the Results
print("Accuracy for Neural Network (Wine):", accuracy_wine)
print("Confusion Matrix (Wine):")
print(confusion_mat_wine)

--------------------------------------------------
Running Classification for Iris Dataset
--------------------------------------------------
Accuracy for Neural Network (Iris): 96.66666666666667
Confusion Matrix (Iris):
[[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]

--------------------------------------------------
Running Classification for Digits Dataset
--------------------------------------------------
Accuracy for Neural Network (Digits): 98.05555555555556
Confusion Matrix (Digits):
[[38  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  0  0  0  0]
 [ 0  0 41  0  0  0  0  0  0  0]
 [ 0  0  0 32  0  1  0  0  0  0]
 [ 0  1  0  0 36  0  0  0  0  0]
 [ 0  0  0  0  0 38  0  0  0  0]
 [ 0  0  0  0  0  0 34  0  1  0]
 [ 0  0  0  0  0  0  0 38  0  0]
 [ 0  4  0  0  0  0  0  0 29  0]
 [ 0  0  0  0  0  0  0  0  0 35]]

--------------------------------------------------
Running Classification for Wine Dataset
--------------------------------------------------
Accuracy for Neural Network (Wine): 63.8